# Generated by Django 3.1.4 on 2020-12-11 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('issue', models.IntegerField(choices=[(0, 'EDUCATION'), (1, 'ELECTRICITY'), (2, 'WATER & SANITATION'), (3, 'HOUSING'), (4, 'INFRASTRUCTURE')], default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=150)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('commenter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
                ('ticket', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Ticketing.ticket')),
            ],
        ),
    ]
