# Generated by Django 3.1.4 on 2020-12-11 08:13

import Profile.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, validators=[Profile.validators.validate_characters])),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Undefined')], default='Undefined')),
                ('race', models.IntegerField(choices=[(0, 'Black'), (1, 'White'), (2, 'Arab'), (3, 'South East Asian'), (4, 'Far East Asian'), (5, 'Undefined')], default='Undefined')),
                ('identification_number', models.CharField(max_length=25, unique=True)),
                ('contact', models.CharField(blank=True, max_length=12, validators=[Profile.validators.validate_characters])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('picture_url', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, validators=[Profile.validators.validate_characters])),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('employee_number', models.CharField(max_length=25, unique=True)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
