# Generated by Django 3.1.4 on 2020-12-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityComplaintData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=150, unique=True)),
                ('water', models.IntegerField()),
                ('infrastructure', models.IntegerField()),
                ('education', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('housing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CityRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=150, unique=True)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CitySolutionFixing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=150, unique=True)),
                ('water_time', models.IntegerField()),
                ('infrastructure_time', models.IntegerField()),
                ('education_time', models.IntegerField()),
                ('electricity_time', models.IntegerField()),
                ('housing_time', models.IntegerField()),
            ],
        ),
    ]
