# Generated by Django 3.1.4 on 2020-12-11 18:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Undefined')], default='Undefined')),
                ('race', models.IntegerField(choices=[(0, 'Black'), (1, 'White'), (2, 'Arab'), (3, 'South East Asian'), (4, 'Far East Asian'), (5, 'Undefined')], default='Undefined')),
                ('type', models.IntegerField(choices=[(0, 'Identity Document'), (1, 'Passport'), (2, 'Social Grant Card')], default='Identity Document')),
                ('status', models.IntegerField(choices=[(0, 'ERROR'), (1, 'ACCEPTED'), (2, 'COMPLETE'), (3, 'INCOMPLETE')], default='INCOMPLETE')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('identification_number', models.CharField(max_length=25, unique=True)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='documents')),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ID.application')),
            ],
        ),
    ]
