# Generated by Django 3.1.4 on 2020-12-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ID', '0003_auto_20201212_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['date_created']},
        ),
    ]
